export type InspirationProject = {
  title: string
  slug: string
  description: string
  imageUrl: string
  memberName?: string
  flooringTypeName: string
  environmentName: string
  order: number
}

export const INSPIRATION_PROJECTS: InspirationProject[] = [
  // ── Manufacturer-sourced projects ──
  {
    title: 'AHF Fog Residential',
    slug: 'ahf-fog-residential',
    description: 'A serene residential installation featuring AHF\'s Fog collection, demonstrating how rubber floor tiles create warm, quiet interiors with enduring style.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/1HG2M005_Fog-ROOM-1.jpg',
    memberName: 'AHF Products',
    flooringTypeName: 'Rubber',
    environmentName: 'Homes',
    order: 1,
  },
  {
    title: 'American Biltrite ABPure Cafeteria',
    slug: 'american-biltrite-abpure-cafeteria',
    description: 'ABPure resilient flooring installed in a high-traffic cafeteria environment, chosen for its hygienic properties and ease of maintenance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/abpure_cafeteria_ABS-38-34.jpg',
    memberName: 'American Biltrite',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Education',
    order: 2,
  },
  {
    title: 'Beauflor Blacktex HD Sheet Vinyl',
    slug: 'beauflor-blacktex-hd',
    description: 'Beauflor\'s Blacktex HD sheet vinyl in Abstract Mocha and Celina Wood pattern — a premium wood-look design for residential and light commercial applications.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/06/Sheet-Vinyl-Blacktex-HD-Abstract_Mocha-Celina-Wood_607M.jpg',
    memberName: 'Beauflor',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Homes',
    order: 3,
  },
  {
    title: 'Bentley Memory Craftsman',
    slug: 'bentley-memory-craftsman',
    description: 'Bentley Mills\' Memory Craftsman in a random ashlar 9x48 plank layout, bringing artisan wood aesthetics to commercial interiors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/07/memory-craftsman-random-ashlar-9x48-1.jpeg',
    memberName: 'Bentley',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Corporate',
    order: 4,
  },
  {
    title: 'CFL FirmFit Intown',
    slug: 'cfl-firmfit-intown',
    description: 'CFL\'s FirmFit Intown rigid core flooring in a modern apartment setting, combining dimensional stability with contemporary wood visuals.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/05/FirmFit-Intown.png',
    memberName: 'CFL',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Apartments',
    order: 5,
  },
  {
    title: 'Congoleum Commercial Installation',
    slug: 'congoleum-commercial',
    description: 'Congoleum resilient flooring deployed in a demanding commercial application, showcasing the brand\'s legacy of durability and design.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/72005-RS.jpg',
    memberName: 'Congoleum',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 6,
  },
  {
    title: 'Gerflor Mipolam Symbioz Healthcare',
    slug: 'gerflor-mipolam-symbioz',
    description: 'Gerflor\'s Mipolam Symbioz homogeneous sheet vinyl in a healthcare setting — designed for hygienic environments requiring seamless, easy-to-clean surfaces.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/10/Healthcare_Mipolam-Symbioz_Homogeneous-Sheet.jpg',
    memberName: 'Gerflor',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 7,
  },
  {
    title: 'HMTX MetStone Graphite',
    slug: 'hmtx-metstone-graphite',
    description: 'HMTX\'s MetStone collection in Graphite, a sophisticated stone-look resilient floor for modern commercial and hospitality spaces.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/MetStone_9620GE32_Graphite_RS.jpg',
    memberName: 'HMTX Industries',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Hospitality',
    order: 8,
  },
  {
    title: 'Interface Daycare Installation',
    slug: 'interface-daycare',
    description: 'Interface resilient flooring in a daycare environment, selected for its safety, comfort, and ease of maintenance in early childhood spaces.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2020/09/IED-DAY-PI001-Daycare_0000_web.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 9,
  },
  {
    title: 'Karndean Ghost Elm Library',
    slug: 'karndean-ghost-elm-library',
    description: 'Karndean\'s Ghost Elm luxury vinyl plank installed in a university library, creating a refined wood-look surface that withstands heavy academic foot traffic.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/04/RCP6544-GhostElm-UniversityLibrary_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 10,
  },
  {
    title: 'Lonseal Lonbead Designer Office',
    slug: 'lonseal-lonbead-office',
    description: 'Lonseal\'s Lonbead resilient flooring in an upscale designer office, combining aesthetic versatility with commercial-grade performance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/07/Lonseal-Lonbead-Designer-Office.jpg',
    memberName: 'Lonseal',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Corporate',
    order: 11,
  },
  {
    title: 'Mannington Prop Hive Swarm',
    slug: 'mannington-prop-hive-swarm',
    description: 'Mannington\'s striking Prop Hive Swarm pattern, demonstrating how resilient flooring can serve as a bold design element in commercial interiors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/130382-Prop-Hive-Swarm.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 12,
  },
  {
    title: 'Mohawk Resilient Collection',
    slug: 'mohawk-resilient',
    description: 'Mohawk\'s resilient flooring showcasing plank-format design with authentic wood visuals for residential and commercial specification.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/07/RES06_48_00.jpg',
    memberName: 'Mohawk',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 13,
  },
  {
    title: 'MSI Bedroom Installation',
    slug: 'msi-bedroom',
    description: 'MSI resilient flooring in a serene residential bedroom, selected for its realistic aesthetics, comfort, and water resistance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/04/Bedroom-0016-HiResJPG-scaled.jpg',
    memberName: 'MSI',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 14,
  },
  {
    title: 'Novalis Alpine Oak Aurora Education',
    slug: 'novalis-alpine-oak-education',
    description: 'Novalis\' Alpine Oak Aurora in an educational setting, delivering warm wood aesthetics with the durability required for high-traffic school corridors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/07/18NOV_002_Educational-Main_Alphine-Oak-Aurora_V02-01_Flat.jpg',
    memberName: 'Novalis',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 15,
  },
  {
    title: 'NOX ECOLAY Terrazzo Education',
    slug: 'nox-ecolay-terrazzo-education',
    description: 'NOX Corp\'s ECOLAY mix-and-match terrazzo-look flooring in an educational facility, combining creative pattern options with rigid core performance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/ECOLAY-mixmatch-terrazzo-education-1.jpg',
    memberName: 'NOX Corp',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Education',
    order: 16,
  },
  {
    title: 'Roppe Rubber Sports Flooring',
    slug: 'roppe-rubber-sports',
    description: 'Roppe rubber flooring at Yale Elementary School in Richardson, Texas — chosen for its superior slip resistance, acoustic comfort, and long-term durability in athletic environments.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/06/YaleES-RichardsonTx-Roppe-Oct178403.jpg',
    memberName: 'Roppe',
    flooringTypeName: 'Rubber',
    environmentName: 'Education',
    order: 17,
  },
  {
    title: 'Shaw UV810 Room Scene',
    slug: 'shaw-uv810-room',
    description: 'Shaw\'s UV810 resilient flooring in a refined room setting, demonstrating the brand\'s commitment to design-forward hard surface products.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/04/UV810_05025_Room.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 18,
  },
  {
    title: 'Tandus Centiva Crayola Experience',
    slug: 'tandus-centiva-crayola',
    description: 'Tandus Centiva flooring installed at the Crayola Experience, a vibrant commercial entertainment venue where creative design meets heavy foot traffic.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2018/03/Crayola_Experience-0002-20.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 19,
  },
  {
    title: 'Tarkett Aria Melodia HO Vinyl',
    slug: 'tarkett-aria-melodia',
    description: 'Tarkett\'s Aria Melodia high-opacity vinyl flooring, offering seamless design coverage ideal for healthcare and medical clinic environments.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/large-Aria-Melodia-HO-Vinyl-066-658-773-.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 20,
  },
  {
    title: 'Torlys RigidTile Firm Designer',
    slug: 'torlys-rigidtile-firm',
    description: 'Torlys\' RigidTile Firm Designer in an industrial commercial application, demonstrating rigid core tile performance under demanding conditions.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/05/RS_RT-FMD28781_RigidTile-Firm-Designer_Industrial_Com-scaled.jpg',
    memberName: 'Torlys',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Corporate',
    order: 21,
  },
  {
    title: 'Windm\u00F6ller Queens Oak Amber',
    slug: 'windmoeller-queens-oak-amber',
    description: 'Windm\u00F6ller\'s Queens Oak Amber luxury resilient plank, bringing premium European oak aesthetics to modern interiors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/Raumbild-Queens-Oak-Amber-PL096C-a4-4c-01.jpg',
    memberName: 'Windm\u00F6ller',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 22,
  },
  // ── Market-application-sourced projects ──
  {
    title: 'Assisted Living Capri Installation',
    slug: 'assisted-living-capri',
    description: 'RigidTile Capri flooring in a senior care facility, selected for its comfort, slip resistance, and calming aesthetic suited to assisted living.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/05/RS_RT-FMP747_RigidTile_Capri_Residential-1-scaled.jpg',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Senior Living',
    order: 23,
  },
  {
    title: 'K-12 Classic Rock Ashlar',
    slug: 'k12-classic-rock-ashlar',
    description: 'Classic Rock / Yacht Rock 18x36 ashlar pattern installed in a K-12 educational environment, delivering visual interest with institutional durability.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/08/classic-rock-yacht-rock-18x36-ashlar.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 24,
  },
  {
    title: 'Grocery Contour LVT Faux Bois',
    slug: 'grocery-contour-lvt',
    description: 'Contour LVT in an abstract faux bois wood-look pattern for a grocery retail environment — durable, easy to clean, and visually appealing.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2020/10/Contour_LVT_Abstract-Faux-Bois-Spread.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 25,
  },
  {
    title: 'Hospital Batiste Chambray',
    slug: 'hospital-batiste-chambray',
    description: 'Batiste Chambray stair-step 18x36 resilient tile in a hospital setting, providing hygienic surfaces with a sophisticated textile-inspired pattern.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/08/batiste-chambray-stair-step-18x36-1.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Healthcare',
    order: 26,
  },
  {
    title: 'Restaurant Contract Vinyl',
    slug: 'restaurant-contract-vinyl',
    description: 'Commercial-grade resilient flooring in a restaurant environment — durability and maintenance are paramount in high-traffic food service settings.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/uc_contract_restaurant_UNT-04.jpg',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Hospitality',
    order: 27,
  },
  {
    title: 'Sonata Boutique Retail',
    slug: 'sonata-boutique-retail',
    description: 'Sonata resilient flooring in a boutique retail setting, combining design sophistication with the wear resistance needed for commercial foot traffic.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/sonata_boutique_CEO-01-03.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 28,
  },
  {
    title: 'Transportation Brunella Marble',
    slug: 'transportation-brunella-marble',
    description: 'Brunella Marble rigid core tile in a transportation facility washroom, combining stone aesthetics with water resistance and easy maintenance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2020/10/RKT3013-G-BrunellaMarble-Bathroom-P1_CM.jpg',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Transportation',
    order: 29,
  },
  {
    title: 'Sustainable Workplace Plank',
    slug: 'sustainable-workplace-plank',
    description: 'Mood Sustainable random ashlar 9x48 plank in a modern workplace, showcasing how resilient flooring combines sustainability with design flexibility.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/08/mood-sustainable-random-ashlar-9x48-1.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 30,
  },
  // ── Local downloaded images — Homes ──
  {
    title: 'Karndean Worn Fabric Oak Kitchen Hallway',
    slug: 'karndean-worn-fabric-oak-kitchen-hallway',
    description: 'Karndean\'s Worn Fabric Oak luxury vinyl plank flows seamlessly from an open-plan kitchen into a hallway, delivering a warm, lived-in wood aesthetic with resilient durability.',
    imageUrl: '/images/inspiration/applications/homes/LLP330-Worn-Fabric-Oak-Kitchen-Hallway-P2_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 31,
  },
  {
    title: 'Karndean Vintage Oregon Oak Bathroom',
    slug: 'karndean-vintage-oregon-oak-bathroom',
    description: 'Karndean\'s Vintage Oregon Oak LVP brings rustic character to a residential bathroom, demonstrating how wood-look resilient flooring excels in wet areas.',
    imageUrl: '/images/inspiration/applications/homes/RCP6531-VintageOregonOak-Bathroom-Cameo_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 32,
  },
  {
    title: 'Karndean Vintage Pine Living Room',
    slug: 'karndean-vintage-pine-living-room',
    description: 'Karndean\'s Vintage Pine creates a warm, character-rich living room floor that pairs beautifully with natural furnishings and casual residential styling.',
    imageUrl: '/images/inspiration/applications/homes/VGW76T-VintagePine-LivingRoom-P1_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 33,
  },
  {
    title: 'Karndean Honey Oak Living Room',
    slug: 'karndean-honey-oak-living-room',
    description: 'A sun-drenched living room finished with Karndean\'s Honey Oak, showcasing how golden wood-tone LVP elevates everyday residential spaces.',
    imageUrl: '/images/inspiration/applications/homes/VGW94T-HoneyOak-LivingRoom-CameoLS2_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 34,
  },
  {
    title: 'Mannington Tangsi Residential Room',
    slug: 'mannington-tangsi-residential',
    description: 'Mannington\'s Tangsi resilient plank in a bright residential room scene, illustrating how light wood visuals open up domestic interiors.',
    imageUrl: '/images/inspiration/applications/homes/GEN_2156DL_Tangsi_RS.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 35,
  },
  {
    title: 'Mannington Tuscan Wheat Residential',
    slug: 'mannington-tuscan-wheat-residential',
    description: 'Mannington\'s Tuscan Wheat plank brings warm, golden-grain aesthetics to a residential setting — a versatile tone that complements a wide range of furniture styles.',
    imageUrl: '/images/inspiration/applications/homes/GEN_2425DL_TuscanWheat_RS.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 36,
  },
  {
    title: 'Karndean Weathered Barnwood Bathroom',
    slug: 'karndean-weathered-barnwood-bathroom',
    description: 'Karndean\'s Weathered Barnwood LVP installed in a residential bathroom, demonstrating the collection\'s rustic character and moisture resistance.',
    imageUrl: '/images/inspiration/applications/homes/RKP8211-Weathered-Barnwood-Bathroom-SQ3_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 37,
  },
  {
    title: 'Torlys RigidTile Modena Kitchen',
    slug: 'torlys-rigidtile-modena-kitchen',
    description: 'Torlys\' RigidTile Modena in a modern residential kitchen, pairing a clean stone-look tile with cabinetry and countertops for a polished everyday aesthetic.',
    imageUrl: '/images/inspiration/applications/homes/RS_RT-FMP748_RigidTile_Modena_Kitchen-1-scaled.jpg',
    memberName: 'Torlys',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 38,
  },
  {
    title: 'Mannington Loft Sunrise Lifestyle',
    slug: 'mannington-loft-sunrise-lifestyle',
    description: 'Mannington\'s Loft Sunrise resilient floor photographed in a relaxed home lifestyle scene, highlighting how resilient flooring anchors modern living spaces.',
    imageUrl: '/images/inspiration/applications/homes/APX060-Lifestyle-Loft-Sunrise_Woman_Dog_Hug.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 39,
  },
  {
    title: 'Mannington Trellis Iron Bathroom',
    slug: 'mannington-trellis-iron-bathroom',
    description: 'Mannington\'s Trellis Iron design in a family bathroom setting, showing how bold patterned resilient tile adds personality to everyday wet spaces.',
    imageUrl: '/images/inspiration/applications/homes/APX070-Lifestyle-Trellis-Iron_Kids_Bathtub_Feet.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 40,
  },
  {
    title: 'Mannington Artemis Cloud Cover Home',
    slug: 'mannington-artemis-cloud-cover-home',
    description: 'Mannington\'s Artemis Cloud Cover resilient plank in a residential room scene, demonstrating the collection\'s light, airy aesthetic for contemporary homes.',
    imageUrl: '/images/inspiration/applications/homes/APX140-Prop-Artemis-Cloud_Cover.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 41,
  },
  {
    title: 'Mannington Swiss Oak Almond Lifestyle',
    slug: 'mannington-swiss-oak-almond-lifestyle',
    description: 'Mannington\'s Swiss Oak Almond rigid core plank shown in a family lifestyle setting, blending European oak character with the comfort of home.',
    imageUrl: '/images/inspiration/applications/homes/MAX740-RGP740-FXP740-RSH-Swiss_Oak-Almond.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 42,
  },
  {
    title: 'Mannington Parisian Oak Croissant Family',
    slug: 'mannington-parisian-oak-croissant-family',
    description: 'Mannington\'s Parisian Oak Croissant plank in a warm family living scene — the French-inspired wood tone creates an inviting backdrop for everyday life.',
    imageUrl: '/images/inspiration/applications/homes/MXP721-RXP721-Lifestyle-Parisian-Oak-Croissant_Girl_Dog_Mom_Dad-1.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 43,
  },
  {
    title: 'Karndean Sausalito Sunrise Living Room',
    slug: 'karndean-sausalito-sunrise-living-room',
    description: 'Karndean\'s Sausalito Sunrise delivers coastal-inspired warmth across a spacious open-plan living room, pairing light stone-look tiles with natural accents.',
    imageUrl: '/images/inspiration/applications/homes/Sausalito_Sunrise_MAX071_RS-FIN.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 44,
  },
  {
    title: 'UC Home Living Room Residential Vinyl',
    slug: 'uc-home-living-room-vinyl',
    description: 'A bright, contemporary residential living room finished with UC sheet vinyl, demonstrating how modern heterogeneous vinyl achieves authentic wood aesthetics.',
    imageUrl: '/images/inspiration/applications/homes/uc_home_living_RVS-56.jpg',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Homes',
    order: 45,
  },
  {
    title: 'UC Home Kitchen Resilient Flooring',
    slug: 'uc-home-kitchen-vinyl',
    description: 'UC resilient vinyl sheet flooring in a clean, modern kitchen — chosen for its water resistance, comfort underfoot, and ease of maintenance.',
    imageUrl: '/images/inspiration/applications/homes/uc_home_kitchen_RUS-35.jpg',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Homes',
    order: 46,
  },
  {
    title: 'UC Home Bedroom Resilient Vinyl',
    slug: 'uc-home-bedroom-vinyl',
    description: 'Resilient vinyl sheet flooring in a tranquil residential bedroom setting, offering cushioned comfort and a wood-look finish that suits any décor.',
    imageUrl: '/images/inspiration/applications/homes/uc_home_bedroom_RFS-43.jpg',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Homes',
    order: 47,
  },
  {
    title: 'UC Home Study Resilient Vinyl',
    slug: 'uc-home-study-vinyl',
    description: 'UC resilient vinyl installed in a home study or office, combining a sophisticated wood-look finish with the practical benefits of easy-clean resilient flooring.',
    imageUrl: '/images/inspiration/applications/homes/uc_home_study_REC-03.jpg',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Homes',
    order: 48,
  },
  // ── Local downloaded images — Apartments ──
  {
    title: 'Beauflor Herringbone Essex Maple Apartment',
    slug: 'beauflor-herringbone-essex-maple-apartment',
    description: 'Beauflor\'s Herringbone Essex Maple sheet vinyl brings a classic parquet pattern to a modern apartment living space with zero-grout ease of maintenance.',
    imageUrl: '/images/inspiration/applications/apartments/33363_HerringboneEssexMaple-ROOM-1-scaled.jpg',
    memberName: 'Beauflor',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Apartments',
    order: 49,
  },
  {
    title: 'Beauflor Herringbone Aurora Oak Apartment',
    slug: 'beauflor-herringbone-aurora-oak-apartment',
    description: 'Beauflor\'s Herringbone Aurora Oak sheet vinyl adds timeless elegance to an apartment interior, delivering a luxury parquet aesthetic without complex installation.',
    imageUrl: '/images/inspiration/applications/apartments/33677_HerringboneAuroraOak-ROOM-1.jpg',
    memberName: 'Beauflor',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Apartments',
    order: 50,
  },
  {
    title: 'Karndean Glacier Oak Apartment Bedroom',
    slug: 'karndean-glacier-oak-apartment-bedroom',
    description: 'Karndean\'s Glacier Oak rigid core plank creates a cool, sophisticated bedroom in a multi-family apartment setting, combining pale wood aesthetics with long-term durability.',
    imageUrl: '/images/inspiration/applications/apartments/SM-RL21-GlacierOak-Bedroom-CameoP1_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Apartments',
    order: 51,
  },
  {
    title: 'Karndean Bleached Grey Walnut Open Kitchen',
    slug: 'karndean-bleached-grey-walnut-open-kitchen',
    description: 'Karndean\'s Bleached Grey Walnut LVP ties together an open-plan kitchen and living area in an apartment, demonstrating how a single resilient floor can unify large living spaces.',
    imageUrl: '/images/inspiration/applications/apartments/WP329-Bleached-Grey-Walnut-Open-Plan-Kitchen-LS3_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Apartments',
    order: 52,
  },
  {
    title: 'Karndean Marrakesh Fumo Open Plan Kitchen',
    slug: 'karndean-marrakesh-fumo-open-kitchen',
    description: 'Karndean\'s Marrakesh and Fumo tile designs combine in an open-plan kitchen, creating an artisan multi-tone stone-look floor suited to contemporary apartment living.',
    imageUrl: '/images/inspiration/applications/apartments/SP220-Marrakesh-SP216-Fumo-OpenPlan-Kitchen-LS3_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Apartments',
    order: 53,
  },
  {
    title: 'Shaw Ascent Journal Apartment Living',
    slug: 'shaw-ascent-journal-apartment',
    description: 'Shaw\'s Ascent collection in the Journal colorway installed in a modern apartment living room, delivering a sophisticated wide-plank wood aesthetic.',
    imageUrl: '/images/inspiration/applications/apartments/Ascent-2832V-05179-Journal-RM-H-scaled.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Apartments',
    order: 54,
  },
  {
    title: 'Shaw Ascent Dwell Apartment Room',
    slug: 'shaw-ascent-dwell-apartment',
    description: 'Shaw\'s Ascent Dwell resilient plank photographed in a vertical room scene, capturing the rich grain variation of this popular apartment-spec flooring collection.',
    imageUrl: '/images/inspiration/applications/apartments/Ascent-2832V-05180-Dwell-RM-V.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Apartments',
    order: 55,
  },
  {
    title: 'Shaw Infinite Shangrila Apartment',
    slug: 'shaw-infinite-shangrila-apartment',
    description: 'Shaw\'s Infinite collection in Shangrila brings a wide-plank, light oak aesthetic to an apartment setting — an ideal blend of design and practical performance.',
    imageUrl: '/images/inspiration/applications/apartments/Infinite-3339V-07199-Shangrila-7in-RM-V.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Apartments',
    order: 56,
  },
  {
    title: 'Torlys Cork XP Elite Burl Oolong Residential',
    slug: 'torlys-cork-xp-elite-burl-oolong',
    description: 'Torlys\' Cork XP Elite in Burl Oolong brings natural warmth and acoustic comfort to a residential room, showcasing cork as a premium sustainable resilient option.',
    imageUrl: '/images/inspiration/applications/apartments/RS_CCUXP-EL134-FSMX_Cork-XP-Elite_Burl-Oolong_res-scaled.jpg',
    memberName: 'Torlys',
    flooringTypeName: 'Cork',
    environmentName: 'Apartments',
    order: 57,
  },
  {
    title: 'Torlys CorkWood XP Designer Fairwinds Oak',
    slug: 'torlys-corkwood-xp-fairwinds-oak',
    description: 'Torlys\' CorkWood XP Designer Fairwinds Oak melds the warmth of wood visuals with the acoustic and comfort properties of cork in a contemporary residential space.',
    imageUrl: '/images/inspiration/applications/apartments/RS_CWXPD-3722-FSMX_CorkWood-XP-Designer_Fairwinds-Oak_res-scaled.jpg',
    memberName: 'Torlys',
    flooringTypeName: 'Cork',
    environmentName: 'Apartments',
    order: 58,
  },
  // ── Local downloaded images — Healthcare / Hospitals ──
  {
    title: 'Interface Healthcare Patient Room',
    slug: 'interface-healthcare-patient-room',
    description: 'Interface resilient LVT in a hospital patient room, providing a hygienic, comfortable surface that supports patient wellbeing and clinical staff workflows.',
    imageUrl: '/images/inspiration/applications/hospitals/IHC-PI001-Patient-Room-EDU_00000_web.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Healthcare',
    order: 59,
  },
  {
    title: 'Interface Healthcare Surgery Suite',
    slug: 'interface-healthcare-surgery-suite',
    description: 'Interface LVT in a surgical suite environment, meeting the stringent hygiene and safety standards required in operating room applications.',
    imageUrl: '/images/inspiration/applications/hospitals/IHC-PI001-Surgery-EDU_00000_web.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Healthcare',
    order: 60,
  },
  {
    title: 'American Biltrite ABPure Hospital Corridor',
    slug: 'abpure-hospital-corridor',
    description: 'ABPure resilient sheet vinyl in a hospital corridor — selected for seamless installation, slip resistance, and the rigorous cleanability demands of acute care facilities.',
    imageUrl: '/images/inspiration/applications/hospitals/abpure_hospital-corridor_ABS-3490.jpg',
    memberName: 'American Biltrite',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 61,
  },
  {
    title: 'American Biltrite ABPure Hospital Multi-Zone',
    slug: 'abpure-hospital-multi-zone',
    description: 'ABPure homogeneous sheet vinyl deployed across multiple hospital zones, demonstrating coordinated color planning for wayfinding and departmental identity.',
    imageUrl: '/images/inspiration/applications/hospitals/abpure_hospital_ABS-36-45-73-83-87.jpg',
    memberName: 'American Biltrite',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 62,
  },
  {
    title: 'Lonseal Lonwood Natural Children\'s Hospital',
    slug: 'lonseal-lonwood-natural-childrens-hospital',
    description: 'Lonseal\'s Lonwood Natural sheet vinyl warms a children\'s hospital waiting room with realistic wood visuals while maintaining the hygienic performance required in pediatric care.',
    imageUrl: '/images/inspiration/applications/hospitals/Lonseal-Lonwood-Natural-Children-Hospital-Waiting-Room.jpg',
    memberName: 'Lonseal',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 63,
  },
  {
    title: 'Lonseal Loneco Hospital Corridor',
    slug: 'lonseal-loneco-hospital-corridor',
    description: 'Lonseal\'s Loneco Linen combined with Lonwood Natural creates a warm, coordinated hospital environment that balances clinical requirements with patient-centered design.',
    imageUrl: '/images/inspiration/applications/hospitals/Lonseal-Loneco-Linen-and-Lonwood-Natural-Hospital.jpg',
    memberName: 'Lonseal',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 64,
  },
  {
    title: 'Batiste Linen Hospitality Healthcare',
    slug: 'batiste-linen-healthcare',
    description: 'Batiste Linen resilient tile installed in a healthcare corridor, where its subtle textile-inspired pattern and easy maintenance make it ideal for high-traffic clinical environments.',
    imageUrl: '/images/inspiration/applications/hospitals/Batiste-Linen-Hospitality.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Healthcare',
    order: 65,
  },
  {
    title: 'Karndean Sandstorm Hospital Reception',
    slug: 'karndean-sandstorm-hospital-reception',
    description: 'Karndean\'s Sandstorm rigid core tile creates a welcoming hospital reception area, pairing a warm stone aesthetic with the durable, easy-clean properties essential in healthcare.',
    imageUrl: '/images/inspiration/applications/hospitals/RKT3010-G-Sandstorm-HospitalReception-LS_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Healthcare',
    order: 66,
  },
  {
    title: 'Tarkett Linoleum Healthcare Hall',
    slug: 'tarkett-linoleum-healthcare-hall',
    description: 'Tarkett linoleum in a healthcare corridor, offering documented bacteriostatic properties and excellent indoor air quality credentials for sensitive clinical environments.',
    imageUrl: '/images/inspiration/applications/hospitals/Lino_Healthcare_Hall_RS.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Linoleum',
    environmentName: 'Healthcare',
    order: 67,
  },
  {
    title: 'Tarkett Linoleum Glasgow Royal Infirmary',
    slug: 'tarkett-linoleum-glasgow-royal-infirmary',
    description: 'Tarkett linoleum installed at Glasgow Royal Infirmary, a landmark installation demonstrating the material\'s proven heritage in large-scale healthcare environments.',
    imageUrl: '/images/inspiration/applications/hospitals/Linoleum_Glasgow-Royal-Infirmary-UK-055-lpr.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Linoleum',
    environmentName: 'Healthcare',
    order: 68,
  },
  {
    title: 'Mipolam Cancer Centre Installation',
    slug: 'mipolam-cancer-centre',
    description: 'Gerflor\'s Mipolam homogeneous sheet vinyl in a modern cancer treatment centre, offering a seamless, highly hygienic surface to support patient care in sensitive oncology environments.',
    imageUrl: '/images/inspiration/applications/hospitals/Mipolam_cancer-centre-04-scaled.jpg',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 69,
  },
  {
    title: 'Hartford Healthcare Envire Sheet Vinyl',
    slug: 'hartford-healthcare-envire',
    description: 'Envire resilient sheet vinyl across a large Hartford Healthcare facility, demonstrating seamless installation at scale with coordinated color selection across departments.',
    imageUrl: '/images/inspiration/applications/hospitals/Hartford-Healthcare-Envire-1-9-2017.jpg',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 70,
  },
  // ── Local downloaded images — Hospitality / Hotels ──
  {
    title: 'Karndean Kilauea Koa Hospitality Study',
    slug: 'karndean-kilauea-koa-hospitality-study',
    description: 'Karndean\'s Kilauea Koa LVP in a hotel study or reading room, delivering rich tropical wood warmth that elevates a guest\'s sense of place.',
    imageUrl: '/images/inspiration/applications/hotels/RKP8124-Kilauea-Koa-Education-Study-Room-LS_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 71,
  },
  {
    title: 'NOX ECOLAY Refined Rustic Hospitality',
    slug: 'nox-ecolay-refined-rustic-hospitality',
    description: 'NOX Corp\'s ECOLAY refined rustic pattern creates a welcoming hotel lobby atmosphere, pairing natural stone-wood aesthetics with the practical benefits of rigid core resilient flooring.',
    imageUrl: '/images/inspiration/applications/hotels/ECOLAY-refined-rustic-hospitality.jpg',
    memberName: 'NOX Corp',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Hospitality',
    order: 72,
  },
  {
    title: 'Interface Sterling Hospitality LVT',
    slug: 'interface-sterling-hospitality',
    description: 'Interface\'s Sterling LVT collection deployed in a hotel setting, combining sleek stone-look aesthetics with the dimensional stability and quiet comfort guests expect.',
    imageUrl: '/images/inspiration/applications/hotels/INC_7863NA_Sterling_RS.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 73,
  },
  {
    title: 'Mannington Tuscan Wheat Hospitality Room',
    slug: 'mannington-tuscan-wheat-hospitality',
    description: 'Mannington\'s Tuscan Wheat resilient plank in a hospitality room scene, offering a warm, neutral wood tone that appeals across a broad range of hotel design briefs.',
    imageUrl: '/images/inspiration/applications/hotels/GEN_2425DL_TuscanWheat_RS-3.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 74,
  },
  {
    title: 'Interface Dried Oak Hotel Room',
    slug: 'interface-dried-oak-hotel-room',
    description: 'Interface\'s Dried Oak rigid core plank creates a calm, sophisticated hotel guest room atmosphere, offering a premium wood aesthetic with the performance demands of hospitality.',
    imageUrl: '/images/inspiration/applications/hotels/INC_INC20010PAD_DriedOak_RS.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Hospitality',
    order: 75,
  },
  {
    title: 'Tarkett Latitude Stone Hotel Lobby',
    slug: 'tarkett-latitude-stone-hotel-lobby',
    description: 'Tarkett\'s Latitude Stone resilient tile creates an impressive hotel lobby floor, offering large-format stone visuals with the lighter weight and easier maintenance of LVT.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/TAR-ID-Latitude-Stone-Cover.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 76,
  },
  {
    title: 'Karndean Pier Oak Hotel Room Scene',
    slug: 'karndean-pier-oak-hotel-room',
    description: 'Karndean\'s Pier Oak rigid core plank in a hotel room, delivering a refined coastal-inspired aesthetic alongside the acoustic and durability performance demanded by hotel specification.',
    imageUrl: '/images/inspiration/applications/hotels/PFSR677_PierOak-ROOM-2.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Hospitality',
    order: 77,
  },
  // ── Local downloaded images — Restaurants ──
  {
    title: 'Karndean Reclaimed Chestnut Bar Restaurant',
    slug: 'karndean-reclaimed-chestnut-bar-restaurant',
    description: 'Karndean\'s Reclaimed Chestnut LVP brings authentic rustic character to a bar and restaurant interior, standing up to spills and heavy service traffic with ease.',
    imageUrl: '/images/inspiration/applications/restaurants/EW21-Reclaimed-Chestnut-Bar-Restaurant-P2_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 78,
  },
  {
    title: 'Karndean Volcanic Slate Bar Restaurant',
    slug: 'karndean-volcanic-slate-bar-restaurant',
    description: 'Karndean\'s Volcanic Slate rigid core tile grounds a bar and restaurant space with dramatic dark stone visuals, providing slip-resistant performance in a high-service environment.',
    imageUrl: '/images/inspiration/applications/restaurants/RKT3001-G-VocanicSlate-BarRestaurant-P_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Hospitality',
    order: 79,
  },
  {
    title: 'Windm\u00F6ller Golden Pine Restaurant',
    slug: 'windmoeller-golden-pine-restaurant',
    description: 'Windm\u00F6ller\'s Golden Pine luxury resilient plank creates a warm, welcoming dining atmosphere — the natural wood tone pairs beautifully with restaurant interior styling.',
    imageUrl: '/images/inspiration/applications/restaurants/Raumbild-Golden-Pine-Mixed-PL077C-a4-4c-01.jpg',
    memberName: 'Windm\u00F6ller',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 80,
  },
  {
    title: 'Karndean Textum Restaurant',
    slug: 'karndean-textum-restaurant',
    description: 'Karndean\'s Textum LVP in a restaurant setting, where its refined woven-texture aesthetic adds visual depth to a dining floor that must withstand daily commercial use.',
    imageUrl: '/images/inspiration/applications/restaurants/WP331-Textum-DS10-3mm-Restaurant-P2_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 81,
  },
  {
    title: 'Forbo Roca Linen Restaurant',
    slug: 'forbo-roca-linen-restaurant',
    description: 'Forbo\'s Roca Linen LVT delivers a textural, neutral surface in a restaurant dining room — a sophisticated backdrop that lets food and furnishings take center stage.',
    imageUrl: '/images/inspiration/applications/restaurants/FF_38321_Roca_Linen_RS_150DPI.jpg',
    memberName: 'Forbo',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 82,
  },
  {
    title: 'Tarkett Texas Granite Lobby',
    slug: 'tarkett-texas-granite-lobby',
    description: 'Tarkett\'s Texas Granite VCT creates a bold, professional lobby statement in a restaurant or hospitality venue, combining classic tile formatting with durable commercial performance.',
    imageUrl: '/images/inspiration/applications/hotels/texas-granite_lobby_VTG-34-30.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Vinyl Composition Tile',
    environmentName: 'Hospitality',
    order: 83,
  },
  // ── Local downloaded images — Workplace / Corporate ──
  {
    title: 'Interface Administrative Healthcare Office',
    slug: 'interface-administrative-office',
    description: 'Interface LVT in a healthcare administrative office, providing a professional, easy-maintenance floor that bridges clinical and corporate environments.',
    imageUrl: '/images/inspiration/applications/workplace/IHC-PI001-Administrative-EDU_00000_web.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 84,
  },
  {
    title: 'Interface Healthcare Lobby LVT',
    slug: 'interface-healthcare-lobby',
    description: 'Interface resilient LVT in a healthcare facility lobby, creating an inviting first impression with a design-forward floor that meets clinical performance standards.',
    imageUrl: '/images/inspiration/applications/workplace/IHC-PI001-Lobby-EDU_00000_web.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 85,
  },
  {
    title: 'Mannington DejaNew Clay Office',
    slug: 'mannington-dejanew-clay-office',
    description: 'Mannington\'s DejaNew Clay LVT in a modern corporate office, where its warm earthy tone adds depth to open-plan workspaces without overwhelming the design.',
    imageUrl: '/images/inspiration/applications/workplace/LVT_DejaNew_DN123809_Clay_RS.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 86,
  },
  {
    title: 'Mannington DejaNew Zinc Corporate',
    slug: 'mannington-dejanew-zinc-corporate',
    description: 'Mannington\'s DejaNew Zinc LVT in a professional corporate environment — a cool industrial-tone plank that complements contemporary open-office design.',
    imageUrl: '/images/inspiration/applications/workplace/LVT_DejaNew_DN123814_Zinc_RS.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 87,
  },
  {
    title: 'Mannington DejaNew Flint Grey Workplace',
    slug: 'mannington-dejanew-flint-grey-workplace',
    description: 'Mannington\'s DejaNew Flint Grey LVT in a contemporary workplace, delivering a sophisticated cool-neutral foundation for modern corporate interiors.',
    imageUrl: '/images/inspiration/applications/workplace/LVT_DejaNew_DN1445108_FlintGrey_RS-1.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 88,
  },
  {
    title: 'Lonseal Architect Firm Office',
    slug: 'lonseal-lonplate-architect-firm',
    description: 'Lonseal\'s Lonplate sheet vinyl in an architecture firm\'s studio space — its refined industrial aesthetic aligns with the creative and professional nature of the environment.',
    imageUrl: '/images/inspiration/applications/workplace/Lonseal-Lonplate-I-Architect-Firm.jpg',
    memberName: 'Lonseal',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Corporate',
    order: 89,
  },
  {
    title: 'Karndean Urban Fabric Oak Corporate Lobby',
    slug: 'karndean-urban-fabric-oak-lobby',
    description: 'Karndean\'s Urban Fabric Oak LVP in a corporate lobby, where its refined textile-inspired wood surface makes a striking first impression for visitors and employees alike.',
    imageUrl: '/images/inspiration/applications/workplace/LLP332-Urban-Fabric-Oak-Lobby-P2_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 90,
  },
  {
    title: 'Sonata Elements Conference Room',
    slug: 'sonata-elements-conference-room',
    description: 'Sonata Elements resilient flooring in a professional conference room, delivering a polished multi-format design that anchors collaborative corporate spaces.',
    imageUrl: '/images/inspiration/applications/workplace/sonata-elements_conference_SEL-2B.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 91,
  },
  {
    title: 'Sonata Elements Open Office',
    slug: 'sonata-elements-open-office',
    description: 'Sonata Elements LVT across an open-plan corporate office, using mixed plank formats to define zones and add design interest to a high-performance commercial floor.',
    imageUrl: '/images/inspiration/applications/workplace/sonata-elements_offices_SEL-1C_1A_1B_2A.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 92,
  },
  {
    title: 'Balustrade Beaux Arts Corporate Office',
    slug: 'balustrade-beaux-arts-corporate',
    description: 'Balustrade Beaux Arts 18x36 resilient tile in a corporate workplace, where its architectural pattern adds grandeur to a professional environment without sacrificing practicality.',
    imageUrl: '/images/inspiration/applications/workplace/Balustrade-Beaux-Arts-Corporate.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 93,
  },
  {
    title: 'Tarkett Color Splash Office Staircase',
    slug: 'tarkett-color-splash-office-staircase',
    description: 'Tarkett\'s Color Splash resilient vinyl on a corporate staircase, introducing vibrant color accents that energize vertical circulation zones within commercial buildings.',
    imageUrl: '/images/inspiration/applications/workplace/TAR-Color-Splash-stairs-VF8-VH8-VK2.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Corporate',
    order: 94,
  },
  {
    title: 'Tarkett Latitude ColorGrain Office',
    slug: 'tarkett-latitude-colorgrain-office',
    description: 'Tarkett\'s Latitude ColorGrain LVT in a modern office environment, where its warm wood-tone variation creates an inviting and design-forward professional space.',
    imageUrl: '/images/inspiration/applications/workplace/TAR-ID-Latitude-ColorGrain_edu.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 95,
  },
  // ── Local downloaded images — Retail ──
  {
    title: 'Novalis Retail Main Installation',
    slug: 'novalis-retail-main',
    description: 'Novalis rigid core flooring in a high-traffic retail main floor, delivering on-trend aesthetics that stand up to the heavy rolling loads and foot traffic of commercial retail.',
    imageUrl: '/images/inspiration/applications/retail/18NOV_002_Retail-Main_TOS_V03-01-Full_Flat.jpg',
    memberName: 'Novalis',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Retail',
    order: 96,
  },
  {
    title: 'Karndean Grey Limed Oak Retail',
    slug: 'karndean-grey-limed-oak-retail',
    description: 'Karndean\'s Grey Limed Oak LVP in a retail environment, creating a fresh, contemporary shopping floor that complements both product displays and store branding.',
    imageUrl: '/images/inspiration/applications/retail/KP138-Grey-Limed-Oak-Retail-LS_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 97,
  },
  {
    title: 'NOX ECOLAY Rustic Edge Gallery',
    slug: 'nox-ecolay-rustic-edge-gallery',
    description: 'NOX Corp\'s ECOLAY rustic edge pattern displayed in a gallery retail space, showing how rigid core resilient flooring can serve as an expressive design statement for premium retail.',
    imageUrl: '/images/inspiration/applications/retail/ECOLAY-rustic-edge-gallery.jpg',
    memberName: 'NOX Corp',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Retail',
    order: 98,
  },
  {
    title: 'Windm\u00F6ller Resilient Planks Retail Scene',
    slug: 'windmoeller-retail-plank-scene',
    description: 'Windm\u00F6ller luxury resilient planks in a retail environment, combining premium European wood-look aesthetics with the durability and maintenance ease required for commercial foot traffic.',
    imageUrl: '/images/inspiration/applications/retail/Raumbild-PL005C-PL045C-a4-4c-01.jpg',
    memberName: 'Windm\u00F6ller',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 99,
  },
  {
    title: 'Windm\u00F6ller Supreme Oak Natural Retail',
    slug: 'windmoeller-supreme-oak-natural-retail',
    description: 'Windm\u00F6ller\'s Supreme Oak Natural resilient plank in a retail setting, demonstrating how a clean, classic European oak visual creates a premium shopping atmosphere.',
    imageUrl: '/images/inspiration/applications/retail/Raumbild-Supreme-Oak-Natural-PL068C-a4-4c-01.jpg',
    memberName: 'Windm\u00F6ller',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 100,
  },
  {
    title: 'GTI Checkers Mall of Africa Retail',
    slug: 'gti-checkers-mall-of-africa',
    description: 'GTI resilient flooring at the Checkers superstore in the Mall of Africa, South Africa — a large-scale retail installation demonstrating commercial-grade resilient flooring at its most ambitious.',
    imageUrl: '/images/inspiration/applications/retail/GTI_Checkers-Mall-Of-Africa-South-Africa-30-scaled.jpg',
    flooringTypeName: 'Vinyl Composition Tile',
    environmentName: 'Retail',
    order: 101,
  },
  {
    title: 'Tarkett VCT Retail Color Mix',
    slug: 'tarkett-vct-retail-color-mix',
    description: 'Tarkett VCT II in a multi-color retail pattern, showing how classic vinyl composition tile can create bold visual environments with high wear resistance and low lifecycle cost.',
    imageUrl: '/images/inspiration/applications/retail/large-Tarkett-VCT-II_CompTile_328_575_588_594_RS_HiRes.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Vinyl Composition Tile',
    environmentName: 'Retail',
    order: 102,
  },
  // ── Local downloaded images — Education ──
  {
    title: 'Lonseal Lonfloor Child Development Center',
    slug: 'lonseal-lonzebra-child-development',
    description: 'Lonseal\'s Lonzebra resilient flooring in a child development center, where its playful patterning and durable surface support active early childhood environments.',
    imageUrl: '/images/inspiration/applications/education/Lonseal-Lonzebra-Child-Development-Center.jpg',
    memberName: 'Lonseal',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Education',
    order: 103,
  },
  {
    title: 'Lonseal Lonfloor Plasma Science Center',
    slug: 'lonseal-lonfloor-plasma-center',
    description: 'Lonseal\'s Lonfloor Flecks in a plasma science center, delivering a robust, easy-clean surface that supports the unique demands of specialized educational and research facilities.',
    imageUrl: '/images/inspiration/applications/education/Lonseal-Lonfloor-Flecks-Psasma-Center.jpg',
    memberName: 'Lonseal',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Education',
    order: 104,
  },
  {
    title: 'Tarkett Linoleum Education Classroom',
    slug: 'tarkett-linoleum-education-classroom',
    description: 'Tarkett linoleum flooring in an educational classroom, providing a naturally sustainable, hygienic surface with excellent acoustic properties for productive learning environments.',
    imageUrl: '/images/inspiration/applications/education/LinoFloor_Education_552_561_601_670_761_RS.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Linoleum',
    environmentName: 'Education',
    order: 105,
  },
  {
    title: 'Tarkett Linoleum Tile Euclid High School',
    slug: 'tarkett-ho-tile-euclid-high-school',
    description: 'Tarkett homogeneous tile installed at Euclid High School, demonstrating the resilience and color consistency of sheet-format vinyl across a major educational facility.',
    imageUrl: '/images/inspiration/applications/education/large-HO_Tile_Euclid_High_School_Oct2020_HiRes-31.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Education',
    order: 106,
  },
  {
    title: 'Tarkett Color Splash Education Staircase',
    slug: 'tarkett-color-splash-education-staircase',
    description: 'Tarkett\'s Color Splash vinyl on a school staircase, bringing vibrant color coordination to vertical surfaces and reinforcing safe wayfinding in educational buildings.',
    imageUrl: '/images/inspiration/applications/education/TAR-Color-Splash-stairs-VF8-VH8-VK2.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Education',
    order: 107,
  },
  {
    title: 'Mannington Alta Alta Resilient Office',
    slug: 'mannington-alta-corporate',
    description: 'Mannington\'s Alta resilient plank in a workplace environment, offering a light, contemporary wood-tone floor suitable for education, healthcare, and corporate interiors.',
    imageUrl: '/images/inspiration/applications/education/Gen_2235DL_Alta_RS.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 108,
  },
  {
    title: 'Fostoria Learning Center Resilient Floor',
    slug: 'fostoria-learning-center',
    description: 'A Fostoria learning center installation demonstrating how resilient flooring can be specified to support both the acoustic and aesthetic needs of modern educational facilities.',
    imageUrl: '/images/inspiration/applications/education/Fostoria-Learning-Center-4-8-17.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 109,
  },
  {
    title: 'AHF Rubber Room Healthcare Education',
    slug: 'ahf-rubber-foam-room-healthcare',
    description: 'AHF\'s rubber-based resilient flooring in a specialized room, delivering superior impact absorption and acoustic comfort for healthcare-adjacent educational settings.',
    imageUrl: '/images/inspiration/applications/education/70001_WhiteRim-70010-ROOM-1-2.jpg',
    memberName: 'AHF Products',
    flooringTypeName: 'Rubber',
    environmentName: 'Education',
    order: 110,
  },
  // ── Local downloaded images — Manufacturer: Mannington ──
  {
    title: 'Mannington VG1 Deco Wrought Iron Commercial',
    slug: 'mannington-vg1-deco-wrought-iron',
    description: 'Mannington\'s VG1 Deco Wrought Iron pattern demonstrates the brand\'s ability to deliver bold, graphic commercial designs that make a strong visual statement in open-plan spaces.',
    imageUrl: '/images/inspiration/manufacturers/mannington/130390-VG1-Deco-Wrought_Iron.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 111,
  },
  {
    title: 'Mannington Mokuzai Sapling Room Scene',
    slug: 'mannington-mokuzai-sapling',
    description: 'Mannington\'s Mokuzai Sapling LVT — a refined, light wood-grain plank that brings natural warmth and a contemporary Japanese-inspired aesthetic to residential and commercial interiors.',
    imageUrl: '/images/inspiration/manufacturers/mannington/APX134-RS-Mokuzai-Sapling.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 112,
  },
  // ── Local downloaded images — Manufacturer: Shaw ──
  {
    title: 'Shaw UV458 Resilient Room Scene',
    slug: 'shaw-uv458-room-scene',
    description: 'Shaw\'s UV458 resilient floor collection in a styled room scene, illustrating the design depth and finish quality available across Shaw\'s hard surface residential program.',
    imageUrl: '/images/inspiration/manufacturers/shaw/UV458_02703_ROOM-scaled.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 113,
  },
  {
    title: 'Shaw Walnut Resilient Plank',
    slug: 'shaw-walnut-resilient-plank',
    description: 'Shaw\'s Walnut resilient plank brings the deep, rich warmth of traditional walnut wood to a residential room scene with the practical advantages of resilient flooring.',
    imageUrl: '/images/inspiration/manufacturers/shaw/Walnut.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 114,
  },
  // ── Local downloaded images — Manufacturer: Mohawk ──
  {
    title: 'Mohawk Thatcher Caledonia Room Scene',
    slug: 'mohawk-thatcher-caledonia',
    description: 'Mohawk\'s Thatcher collection in Caledonia, a warm grey-toned resilient plank that suits both residential and light commercial applications with its understated sophistication.',
    imageUrl: '/images/inspiration/manufacturers/mohawk/Thatcher_961-Caledonia_RM.jpg',
    memberName: 'Mohawk',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 115,
  },
  {
    title: 'Mohawk Westinghouse Carmel Room Scene',
    slug: 'mohawk-westinghouse-carmel',
    description: 'Mohawk\'s Westinghouse collection in Carmel delivers a warm honey-oak plank aesthetic that creates a bright, welcoming residential interior.',
    imageUrl: '/images/inspiration/manufacturers/mohawk/Westinghouse_916-Carmel_RM.jpg',
    memberName: 'Mohawk',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 116,
  },
  {
    title: 'Mohawk Franklin Berkley Room Scene',
    slug: 'mohawk-franklin-berkley',
    description: 'Mohawk\'s Franklin collection in Berkley provides a sophisticated, mid-toned oak resilient plank ideal for residential living rooms and open-plan family spaces.',
    imageUrl: '/images/inspiration/manufacturers/mohawk/Franklin_830-Berkley_RM.jpg',
    memberName: 'Mohawk',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 117,
  },
  {
    title: 'Mohawk 64542 Residential Collection',
    slug: 'mohawk-64542-residential',
    description: 'Mohawk\'s resilient collection 64542 in a light-toned residential room scene, demonstrating a clean and versatile plank that suits contemporary home interiors.',
    imageUrl: '/images/inspiration/manufacturers/mohawk/64542_595M_00.jpg',
    memberName: 'Mohawk',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 118,
  },
  // ── Local downloaded images — Manufacturer: Tarkett ──
  {
    title: 'Tarkett AcczentFlourish Corporate Office',
    slug: 'tarkett-acczentflourish-corporate',
    description: 'Tarkett\'s AcczentFlourish heterogeneous vinyl in a corporate office environment, combining design flexibility with the proven durability of Tarkett\'s commercial vinyl platform.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/AcczentFlourish_VYL_Corporate_R_02_HiRes.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Corporate',
    order: 119,
  },
  {
    title: 'Tarkett Contour LVT Creekside',
    slug: 'tarkett-contour-lvt-creekside',
    description: 'Tarkett\'s Contour LVT in Creekside — a cool stone-look luxury vinyl tile that brings natural material aesthetics to commercial spaces with minimal maintenance requirements.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/Contour_LVT_Creekside.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 120,
  },
  {
    title: 'Tarkett Contour LVT Arrowroot',
    slug: 'tarkett-contour-lvt-arrowroot',
    description: 'Tarkett\'s Contour LVT in Arrowroot delivers a warm, textural stone-look tile that works equally well across retail, corporate, and healthcare environments.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/Contour_LVT_Arrowroot_RS.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 121,
  },
  {
    title: 'Forbo Herringbone Charcoal LVT',
    slug: 'forbo-herringbone-charcoal-lvt',
    description: 'Forbo\'s Herringbone Charcoal luxury vinyl tile delivers a bold geometric pattern with a sophisticated dark palette — ideal for statement retail or hospitality floors.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/FF_14582_Herringbone_Charcoal_RS_150DPI.jpg',
    memberName: 'Forbo',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Hospitality',
    order: 122,
  },
  {
    title: 'Forbo Natural Cliff Oak LVT',
    slug: 'forbo-natural-cliff-oak-lvt',
    description: 'Forbo\'s Natural Cliff Oak LVT captures the rugged beauty of weathered oak in a resilient format, suited to contemporary residential and commercial interiors.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/FF_01491_Natural_Cliff-Oak_RS_150DPI.jpg',
    memberName: 'Forbo',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 123,
  },
  {
    title: 'Forbo Basketcase Granite Grey LVT',
    slug: 'forbo-basketcase-granite-grey-lvt',
    description: 'Forbo\'s Basketcase Granite Grey LVT brings a woven-pattern concrete aesthetic to commercial flooring, offering a graphic, textural surface for modern workplace and retail environments.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/FF_01462_Basketcase_GraniteGrey_150DPI_crop.jpg',
    memberName: 'Forbo',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 124,
  },
  {
    title: 'Tarkett Flourish Essence Brushed Oak',
    slug: 'tarkett-flourish-essence-brushed-oak',
    description: 'Tarkett\'s Flourish Essence in Brushed Oak provides a subtly textured wood-look resilient plank, perfectly suited to healthcare and education environments where warmth and cleanability are both priorities.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/Flourish_Essence_BrushedOak_Medium.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 125,
  },
  {
    title: 'Tarkett Flourish Reflection Granito',
    slug: 'tarkett-flourish-reflection-granito',
    description: 'Tarkett\'s Flourish Reflection in Granito Warm Grey delivers a polished stone-look vinyl ideal for healthcare corridors and clinical reception areas.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/Flourish_Reflection_Granito_WarmGrey.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 126,
  },
  {
    title: 'Tarkett Flourish Serenade Concrete',
    slug: 'tarkett-flourish-serenade-concrete',
    description: 'Tarkett\'s Flourish Serenade in Concrete Cool Grey creates a calm, professional atmosphere in healthcare and education spaces where a modern aesthetic and easy maintenance are essential.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/Flourish_Serenade_Concrete_CoolGrey.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Education',
    order: 127,
  },
  {
    title: 'Tarkett Optima Bioskills Lab',
    slug: 'tarkett-optima-bioskills-lab',
    description: 'Tarkett\'s Optima homogeneous vinyl in a bioskills laboratory, where its seamless surface and outstanding chemical resistance support the stringent hygiene demands of specialized medical training environments.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/Optima_Bioskills-Lab-V1-1438.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 128,
  },
  {
    title: 'Tarkett Optima Spa Portrait',
    slug: 'tarkett-optima-spa-portrait',
    description: 'Tarkett\'s Optima HO Meteor homogeneous vinyl in a spa or wellness environment, delivering a calming, seamless surface with the hygiene performance required in therapeutic settings.',
    imageUrl: '/images/inspiration/manufacturers/tarkett/Optima_HO_METEOR-SPA-PORTRAIT_v2.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 129,
  },
  {
    title: 'Tarkett iD Inspiration Rubber Grey Riven',
    slug: 'tarkett-id-inspiration-grey-riven',
    description: 'Tarkett\'s iD Inspiration Grey Riven Slate LVT in a family kitchen setting, demonstrating how large-format stone-look resilient tiles bring bold character to everyday residential spaces.',
    imageUrl: '/images/inspiration/applications/homes/ST16-Grey-Riven-Slate-DS10-3mm-Family-Kitchen-Cameo-LS2_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 130,
  },
]
