export type InspirationProject = {
  title: string
  slug: string
  description: string
  imageUrl: string
  memberName?: string
  flooringTypeName: string
  environmentName: string
  order: number
}

export const INSPIRATION_PROJECTS: InspirationProject[] = [
  // ── Manufacturer-sourced projects ──
  {
    title: 'AHF Fog Residential',
    slug: 'ahf-fog-residential',
    description: 'A serene residential installation featuring AHF\'s Fog collection, demonstrating how rubber floor tiles create warm, quiet interiors with enduring style.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/1HG2M005_Fog-ROOM-1.jpg',
    memberName: 'AHF Products',
    flooringTypeName: 'Rubber',
    environmentName: 'Homes',
    order: 1,
  },
  {
    title: 'American Biltrite ABPure Cafeteria',
    slug: 'american-biltrite-abpure-cafeteria',
    description: 'ABPure resilient flooring installed in a high-traffic cafeteria environment, chosen for its hygienic properties and ease of maintenance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/abpure_cafeteria_ABS-38-34.jpg',
    memberName: 'American Biltrite',
    flooringTypeName: 'Homogeneous Sheet Vinyl',
    environmentName: 'Education',
    order: 2,
  },
  {
    title: 'Beauflor Blacktex HD Sheet Vinyl',
    slug: 'beauflor-blacktex-hd',
    description: 'Beauflor\'s Blacktex HD sheet vinyl in Abstract Mocha and Celina Wood pattern — a premium wood-look design for residential and light commercial applications.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/06/Sheet-Vinyl-Blacktex-HD-Abstract_Mocha-Celina-Wood_607M.jpg',
    memberName: 'Beauflor',
    flooringTypeName: 'Heterogeneous Sheet Vinyl',
    environmentName: 'Homes',
    order: 3,
  },
  {
    title: 'Bentley Memory Craftsman',
    slug: 'bentley-memory-craftsman',
    description: 'Bentley Mills\' Memory Craftsman in a random ashlar 9x48 plank layout, bringing artisan wood aesthetics to commercial interiors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/07/memory-craftsman-random-ashlar-9x48-1.jpeg',
    memberName: 'Bentley',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Corporate',
    order: 4,
  },
  {
    title: 'CFL FirmFit Intown',
    slug: 'cfl-firmfit-intown',
    description: 'CFL\'s FirmFit Intown rigid core flooring in a modern apartment setting, combining dimensional stability with contemporary wood visuals.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/05/FirmFit-Intown.png',
    memberName: 'CFL',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Apartments',
    order: 5,
  },
  {
    title: 'Congoleum Commercial Installation',
    slug: 'congoleum-commercial',
    description: 'Congoleum resilient flooring deployed in a demanding commercial application, showcasing the brand\'s legacy of durability and design.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/72005-RS.jpg',
    memberName: 'Congoleum',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 6,
  },
  {
    title: 'Gerflor Mipolam Symbioz Healthcare',
    slug: 'gerflor-mipolam-symbioz',
    description: 'Gerflor\'s Mipolam Symbioz homogeneous sheet vinyl in a healthcare setting — designed for hygienic environments requiring seamless, easy-to-clean surfaces.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/10/Healthcare_Mipolam-Symbioz_Homogeneous-Sheet.jpg',
    memberName: 'Gerflor',
    flooringTypeName: 'Homogeneous Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 7,
  },
  {
    title: 'HMTX MetStone Graphite',
    slug: 'hmtx-metstone-graphite',
    description: 'HMTX\'s MetStone collection in Graphite, a sophisticated stone-look resilient floor for modern commercial and hospitality spaces.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/MetStone_9620GE32_Graphite_RS.jpg',
    memberName: 'HMTX Industries',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Hospitality',
    order: 8,
  },
  {
    title: 'Interface Daycare Installation',
    slug: 'interface-daycare',
    description: 'Interface resilient flooring in a daycare environment, selected for its safety, comfort, and ease of maintenance in early childhood spaces.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2020/09/IED-DAY-PI001-Daycare_0000_web.jpg',
    memberName: 'Interface',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 9,
  },
  {
    title: 'Karndean Ghost Elm Library',
    slug: 'karndean-ghost-elm-library',
    description: 'Karndean\'s Ghost Elm luxury vinyl plank installed in a university library, creating a refined wood-look surface that withstands heavy academic foot traffic.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/04/RCP6544-GhostElm-UniversityLibrary_CM.jpg',
    memberName: 'Karndean',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 10,
  },
  {
    title: 'Lonseal Lonbead Designer Office',
    slug: 'lonseal-lonbead-office',
    description: 'Lonseal\'s Lonbead resilient flooring in an upscale designer office, combining aesthetic versatility with commercial-grade performance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/07/Lonseal-Lonbead-Designer-Office.jpg',
    memberName: 'Lonseal',
    flooringTypeName: 'Heterogeneous Sheet Vinyl',
    environmentName: 'Corporate',
    order: 11,
  },
  {
    title: 'Mannington Prop Hive Swarm',
    slug: 'mannington-prop-hive-swarm',
    description: 'Mannington\'s striking Prop Hive Swarm pattern, demonstrating how resilient flooring can serve as a bold design element in commercial interiors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/130382-Prop-Hive-Swarm.jpg',
    memberName: 'Mannington',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 12,
  },
  {
    title: 'Mohawk Resilient Collection',
    slug: 'mohawk-resilient',
    description: 'Mohawk\'s resilient flooring showcasing plank-format design with authentic wood visuals for residential and commercial specification.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/07/RES06_48_00.jpg',
    memberName: 'Mohawk',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 13,
  },
  {
    title: 'MSI Bedroom Installation',
    slug: 'msi-bedroom',
    description: 'MSI resilient flooring in a serene residential bedroom, selected for its realistic aesthetics, comfort, and water resistance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/04/Bedroom-0016-HiResJPG-scaled.jpg',
    memberName: 'MSI',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Homes',
    order: 14,
  },
  {
    title: 'Novalis Alpine Oak Aurora Education',
    slug: 'novalis-alpine-oak-education',
    description: 'Novalis\' Alpine Oak Aurora in an educational setting, delivering warm wood aesthetics with the durability required for high-traffic school corridors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/07/18NOV_002_Educational-Main_Alphine-Oak-Aurora_V02-01_Flat.jpg',
    memberName: 'Novalis',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 15,
  },
  {
    title: 'NOX ECOLAY Terrazzo Education',
    slug: 'nox-ecolay-terrazzo-education',
    description: 'NOX Corp\'s ECOLAY mix-and-match terrazzo-look flooring in an educational facility, combining creative pattern options with rigid core performance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/02/ECOLAY-mixmatch-terrazzo-education-1.jpg',
    memberName: 'NOX Corp',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Education',
    order: 16,
  },
  {
    title: 'Roppe Rubber Sports Flooring',
    slug: 'roppe-rubber-sports',
    description: 'Roppe rubber flooring at Yale Elementary School in Richardson, Texas — chosen for its superior slip resistance, acoustic comfort, and long-term durability in athletic environments.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2019/06/YaleES-RichardsonTx-Roppe-Oct178403.jpg',
    memberName: 'Roppe',
    flooringTypeName: 'Rubber',
    environmentName: 'Education',
    order: 17,
  },
  {
    title: 'Shaw UV810 Room Scene',
    slug: 'shaw-uv810-room',
    description: 'Shaw\'s UV810 resilient flooring in a refined room setting, demonstrating the brand\'s commitment to design-forward hard surface products.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/04/UV810_05025_Room.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 18,
  },
  {
    title: 'Tandus Centiva Crayola Experience',
    slug: 'tandus-centiva-crayola',
    description: 'Tandus Centiva flooring installed at the Crayola Experience, a vibrant commercial entertainment venue where creative design meets heavy foot traffic.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2018/03/Crayola_Experience-0002-20.jpg',
    memberName: 'Shaw',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 19,
  },
  {
    title: 'Tarkett Aria Melodia HO Vinyl',
    slug: 'tarkett-aria-melodia',
    description: 'Tarkett\'s Aria Melodia high-opacity vinyl flooring, offering seamless design coverage ideal for healthcare and medical clinic environments.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/large-Aria-Melodia-HO-Vinyl-066-658-773-.jpg',
    memberName: 'Tarkett',
    flooringTypeName: 'Heterogeneous Sheet Vinyl',
    environmentName: 'Healthcare',
    order: 20,
  },
  {
    title: 'Torlys RigidTile Firm Designer',
    slug: 'torlys-rigidtile-firm',
    description: 'Torlys\' RigidTile Firm Designer in an industrial commercial application, demonstrating rigid core tile performance under demanding conditions.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/05/RS_RT-FMD28781_RigidTile-Firm-Designer_Industrial_Com-scaled.jpg',
    memberName: 'Torlys',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Corporate',
    order: 21,
  },
  {
    title: 'Windm\u00F6ller Queens Oak Amber',
    slug: 'windmoeller-queens-oak-amber',
    description: 'Windm\u00F6ller\'s Queens Oak Amber luxury resilient plank, bringing premium European oak aesthetics to modern interiors.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/Raumbild-Queens-Oak-Amber-PL096C-a4-4c-01.jpg',
    memberName: 'Windm\u00F6ller',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Homes',
    order: 22,
  },
  // ── Market-application-sourced projects ──
  {
    title: 'Assisted Living Capri Installation',
    slug: 'assisted-living-capri',
    description: 'RigidTile Capri flooring in a senior care facility, selected for its comfort, slip resistance, and calming aesthetic suited to assisted living.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/05/RS_RT-FMP747_RigidTile_Capri_Residential-1-scaled.jpg',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Senior Living',
    order: 23,
  },
  {
    title: 'K-12 Classic Rock Ashlar',
    slug: 'k12-classic-rock-ashlar',
    description: 'Classic Rock / Yacht Rock 18x36 ashlar pattern installed in a K-12 educational environment, delivering visual interest with institutional durability.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/08/classic-rock-yacht-rock-18x36-ashlar.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Education',
    order: 24,
  },
  {
    title: 'Grocery Contour LVT Faux Bois',
    slug: 'grocery-contour-lvt',
    description: 'Contour LVT in an abstract faux bois wood-look pattern for a grocery retail environment — durable, easy to clean, and visually appealing.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2020/10/Contour_LVT_Abstract-Faux-Bois-Spread.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 25,
  },
  {
    title: 'Hospital Batiste Chambray',
    slug: 'hospital-batiste-chambray',
    description: 'Batiste Chambray stair-step 18x36 resilient tile in a hospital setting, providing hygienic surfaces with a sophisticated textile-inspired pattern.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/08/batiste-chambray-stair-step-18x36-1.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Healthcare',
    order: 26,
  },
  {
    title: 'Restaurant Contract Vinyl',
    slug: 'restaurant-contract-vinyl',
    description: 'Commercial-grade resilient flooring in a restaurant environment — durability and maintenance are paramount in high-traffic food service settings.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/uc_contract_restaurant_UNT-04.jpg',
    flooringTypeName: 'Heterogeneous Sheet Vinyl',
    environmentName: 'Hospitality',
    order: 27,
  },
  {
    title: 'Sonata Boutique Retail',
    slug: 'sonata-boutique-retail',
    description: 'Sonata resilient flooring in a boutique retail setting, combining design sophistication with the wear resistance needed for commercial foot traffic.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2022/03/sonata_boutique_CEO-01-03.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Retail',
    order: 28,
  },
  {
    title: 'Transportation Brunella Marble',
    slug: 'transportation-brunella-marble',
    description: 'Brunella Marble rigid core tile in a transportation facility washroom, combining stone aesthetics with water resistance and easy maintenance.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2020/10/RKT3013-G-BrunellaMarble-Bathroom-P1_CM.jpg',
    flooringTypeName: 'Rigid Core',
    environmentName: 'Transportation',
    order: 29,
  },
  {
    title: 'Sustainable Workplace Plank',
    slug: 'sustainable-workplace-plank',
    description: 'Mood Sustainable random ashlar 9x48 plank in a modern workplace, showcasing how resilient flooring combines sustainability with design flexibility.',
    imageUrl: 'https://rfci.com/wp-content/uploads/2023/08/mood-sustainable-random-ashlar-9x48-1.jpg',
    flooringTypeName: 'Flexible LVT',
    environmentName: 'Corporate',
    order: 30,
  },
]
